### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by pythonLoader** [ggonnella/textformats#1]
Hello, 

I can't install the package using pip. At first, there was an issue with the nim installation. After the proper nim version was installed, the following stack trace was shown:

`     running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib
      creating build/lib/textformats
      copying textformats/error.py -> build/lib/textformats
      copying textformats/textformats.py -> build/lib/textformats
      copying textformats/__init__.py -> build/lib/textformats
      running egg_info
      writing textformats.egg-info/PKG-INFO
      writing dependency_links to textformats.egg-info/dependency_links.txt
      writing top-level names to textformats.egg-info/top_level.txt
      reading manifest file 'textformats.egg-info/SOURCES.txt'
      writing manifest file 'textformats.egg-info/SOURCES.txt'
      Compiling py bindings
      cp py_bindings/src/py_bindings.nim.cfg py_bindings/src/py_bindings.nim.cfg.orig
      if [[ "$(arch)" == "arm64" ]]; then \
        echo '--passC:"-arch arm64 -flto"' >> py_bindings/src/py_bindings.nim.cfg; \
        echo '--passL:"-arch arm64 -flto"' >> py_bindings/src/py_bindings.nim.cfg; \
      else \
        echo '--passC:"-flto"' >> py_bindings/src/py_bindings.nim.cfg; \
        echo '--passL:"-flto"' >> py_bindings/src/py_bindings.nim.cfg; \
      fi
      /bin/sh: 1: [[: not found
      cd py_bindings && nimble build
        Verifying dependencies for py_bindings@1.2.2
          Prompt: No local packages.json found, download it from internet? [y/N]
      io.nim(142)              raiseEOF
      Error: unhandled exception: EOF reached [EOFError]
          Answer: Makefile:51: recipe for target 'py_bindings/py_bindings.so' failed
      make: *** [py_bindings/py_bindings.so] Error 1
      error: can't copy '/tmp/pip-install-ezbg9_ru/textformats_42344d338030414c90f15332e9ffd900/build/temp.linux-x86_64-cpython-310/py_bindings/py_bindings.so': doesn't exist or not a regular file
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for textformats`
  Is there any issue regarding building wheel that must be addressed here?

**Comment by ggonnella** [comment]
Dear Shashata Sawmya,

the error originates from the fact that the lines are apparently interpreted in your system by "sh" and not "bash". Sh does not have "[[".

Let me think of a solution to make this not happen. Maybe in the meantime you can alias bash to sh before running pip:

```
alias sh="bash"
pip install .
```

Please let me know if it worked.

Giorgio 

On 17 April 2022 04:06:30 CEST, Shashata Sawmya ***@***.***> wrote:
>Hello, 
>
>I can't install the package using pip. At first, there was an issue with the nim installation. After the proper nim version was installed, the following stack trace was shown:
>
>`     running bdist_wheel
>      running build
>      running build_py
>      creating build
>      creating build/lib
>      creating build/lib/textformats
>      copying textformats/error.py -> build/lib/textformats
>      copying textformats/textformats.py -> build/lib/textformats
>      copying textformats/__init__.py -> build/lib/textformats
>      running egg_info
>      writing textformats.egg-info/PKG-INFO
>      writing dependency_links to textformats.egg-info/dependency_links.txt
>      writing top-level names to textformats.egg-info/top_level.txt
>      reading manifest file 'textformats.egg-info/SOURCES.txt'
>      writing manifest file 'textformats.egg-info/SOURCES.txt'
>      Compiling py bindings
>      cp py_bindings/src/py_bindings.nim.cfg py_bindings/src/py_bindings.nim.cfg.orig
>      if [[ "$(arch)" == "arm64" ]]; then \
>        echo '--passC:"-arch arm64 -flto"' >> py_bindings/src/py_bindings.nim.cfg; \
>        echo '--passL:"-arch arm64 -flto"' >> py_bindings/src/py_bindings.nim.cfg; \
>      else \
>        echo '--passC:"-flto"' >> py_bindings/src/py_bindings.nim.cfg; \
>        echo '--passL:"-flto"' >> py_bindings/src/py_bindings.nim.cfg; \
>      fi
>      /bin/sh: 1: [[: not found
>      cd py_bindings && nimble build
>        Verifying dependencies for ***@***.***
>          Prompt: No local packages.json found, download it from internet? [y/N]
>      io.nim(142)              raiseEOF
>      Error: unhandled exception: EOF reached [EOFError]
>          Answer: Makefile:51: recipe for target 'py_bindings/py_bindings.so' failed
>      make: *** [py_bindings/py_bindings.so] Error 1
>      error: can't copy '/tmp/pip-install-ezbg9_ru/textformats_42344d338030414c90f15332e9ffd900/build/temp.linux-x86_64-cpython-310/py_bindings/py_bindings.so': doesn't exist or not a regular file
>      [end of output]
>  
>  note: This error originates from a subprocess, and is likely not a problem with pip.
>  ERROR: Failed building wheel for textformats`
>  Is there any issue regarding building wheel that must be addressed here? 
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/ggonnella/textformats/issues/1
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
-- 
Dr. Giorgio Gonnella

**Comment by ggonnella** [comment]
Adding the line:

SHELL := /bin/bash

in the Makefile is the right solution to the problem.

On 17 April 2022 04:06:30 CEST, Shashata Sawmya ***@***.***> wrote:
>Hello, 
>
>I can't install the package using pip. At first, there was an issue with the nim installation. After the proper nim version was installed, the following stack trace was shown:
>
>`     running bdist_wheel
>      running build
>      running build_py
>      creating build
>      creating build/lib
>      creating build/lib/textformats
>      copying textformats/error.py -> build/lib/textformats
>      copying textformats/textformats.py -> build/lib/textformats
>      copying textformats/__init__.py -> build/lib/textformats
>      running egg_info
>      writing textformats.egg-info/PKG-INFO
>      writing dependency_links to textformats.egg-info/dependency_links.txt
>      writing top-level names to textformats.egg-info/top_level.txt
>      reading manifest file 'textformats.egg-info/SOURCES.txt'
>      writing manifest file 'textformats.egg-info/SOURCES.txt'
>      Compiling py bindings
>      cp py_bindings/src/py_bindings.nim.cfg py_bindings/src/py_bindings.nim.cfg.orig
>      if [[ "$(arch)" == "arm64" ]]; then \
>        echo '--passC:"-arch arm64 -flto"' >> py_bindings/src/py_bindings.nim.cfg; \
>        echo '--passL:"-arch arm64 -flto"' >> py_bindings/src/py_bindings.nim.cfg; \
>      else \
>        echo '--passC:"-flto"' >> py_bindings/src/py_bindings.nim.cfg; \
>        echo '--passL:"-flto"' >> py_bindings/src/py_bindings.nim.cfg; \
>      fi
>      /bin/sh: 1: [[: not found
>      cd py_bindings && nimble build
>        Verifying dependencies for ***@***.***
>          Prompt: No local packages.json found, download it from internet? [y/N]
>      io.nim(142)              raiseEOF
>      Error: unhandled exception: EOF reached [EOFError]
>          Answer: Makefile:51: recipe for target 'py_bindings/py_bindings.so' failed
>      make: *** [py_bindings/py_bindings.so] Error 1
>      error: can't copy '/tmp/pip-install-ezbg9_ru/textformats_42344d338030414c90f15332e9ffd900/build/temp.linux-x86_64-cpython-310/py_bindings/py_bindings.so': doesn't exist or not a regular file
>      [end of output]
>  
>  note: This error originates from a subprocess, and is likely not a problem with pip.
>  ERROR: Failed building wheel for textformats`
>  Is there any issue regarding building wheel that must be addressed here? 
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/ggonnella/textformats/issues/1
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
-- 
Dr. Giorgio Gonnella

**Comment by ggonnella** [comment]
PS:
You wrote:
"At first, there was an issue with the nim installation. After the proper nim version was installed, ..."

Could you kindly give me some more detail regarding that issue too? I'm trying to streamline the installation process for every user as much as possible and that information could help.

**Comment by pythonLoader** [comment]
Hello Giorgio Gonnella,

My initial installation through pip produced this error. 
`    
      PROBLEM:
      
      For installing a source extension developed in Nim, the Nim compiler
      is necessary. However, it could not be located in the system.
      
      SOLUTION:
      
      Is the Nim compiler already installed?
      
      [Yes] => in case the compiler is not in the PATH,
               provide the Nim compiler location as follows:
      
                 env PATH=$PATH:/path/to/nim/ pip install textformats
      
      [No] => install Nim, using one of the following systems
              and run 'pip install textformats' afterwards
      
        [pip]        pip install choosenim_install
      
        [conda]      conda install nim
      
        [choosenim]  curl https://nim-lang.org/choosenim/init.sh -sSf | sh
      
        [pre-compiled nim] see: https://nim-lang.org/install_unix.html
      
`
I did a conda install nim, but the conda repo has version 1.4.8. So, the pip install didn't work again, I installed the nim version 1.6 from the official site which produced the next error as specified in this issue. You can create a sh file that takes care of all installation including nim. It might make the installation much easier.

The main issue has been resolved now. It was indeed a bash vs sh problem.

**Comment by ggonnella** [comment]
I close this issue, since it has been solved now

**Comment by ggonnella** [comment]
Thank you very much for the report!

I added that error message you got, and it seems that at least it was informative enough, that you could solve the problem.

However, based on your experience I should probably:
- explicitly tell in that message which Nim version is needed
- remove/flag the conda option until they update the available Nim version
- add the Nim installation to an .sh file as you suggest - or directly to the Makefile -- this is more difficult for the installation way via "pip install textformats", however

I hope you enjoy Textformats.

-- 
Dr. Giorgio Gonnella
